name: Handle student test data
on:
  repository_dispatch:
    types: [student_test_results]

jobs:
  process-student-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out teacher repo
        uses: actions/checkout@v4

      - name: Fetch artifacts from student
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # 1) Hent ut client_payload fra event
          STUDENT_REPO="${{ github.event.client_payload.student_repo }}"
          RUN_ID="${{ github.event.client_payload.run_id }}"
          
          echo "Student repo: $STUDENT_REPO"
          echo "Run ID: $RUN_ID"

          # 2) Sjekk tilgjengelige artifacts i studentrepoet for den kjøringen
          gh api \
            repos/$STUDENT_REPO/actions/runs/$RUN_ID/artifacts \
            --jq '.artifacts[] | {id: .id, name: .name, size_in_bytes: .size_in_bytes}'

          # 3) Hvis du finner artifacten du vil ha (f.eks. coverage),
          #    lagre ID-en og last den ned:
          ARTIFACT_ID=$(gh api repos/$STUDENT_REPO/actions/runs/$RUN_ID/artifacts --jq '.artifacts[] | select(.name=="coverage") | .id')

          echo "Artifact ID = $ARTIFACT_ID"

          # 4) Last ned artifact til en folder i teacher-run
          if [ -n "$ARTIFACT_ID" ]; then
            gh api \
              repos/$STUDENT_REPO/actions/artifacts/$ARTIFACT_ID/zip \
              --silent --output coverage.zip

            unzip coverage.zip -d coverage_extracted
            echo "Coverage artifact extracted!"
          else
            echo "No coverage artifact found!"
          fi


